name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - uses: 1password/load-secrets-action/configure@v2
      with:
        service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint
    # - name: Install and sign in 1Password CLI using Connect token
    #   uses: 1password/load-secrets-action@v3
    #     env:
    #       OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    #       SECRET: op://app-cicd/hello-world/secret
    #       OP_ENV_FILE: "./.env.1password" # see tests/.env.tpl for example
    - name: Build project
      run: npm run build
