name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint
    - name: Install and sign in 1Password CLI using Connect token
      uses: 1Password/op-action@v2
      with:
        op-connect-token: ${{ secrets.OP_CONNECT_TOKEN }}
    - name: Build project
      run: npm run build
